
server:
    port: 8084

spring:
    datasource:
        url: jdbc:oracle:thin:@localhost:1521/orcl
        username: jpashop
        password: jpashop
        driver-class-name: oracle.jdbc.driver.OracleDriver
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
